"""Reference data: cities, districts and the camera network.

All coordinates are real geography so the map behaves sensibly; the sightings
themselves are fiction generated by the demo simulator and always tagged
`is_demo = 1`.
"""

import time
import random

from . import db as dbmod
from .services import sightings as sightings_service

CITIES = [
    # id, name, country, lat, lon, zoom, tz, primary
    ("nyc",     "NEW YORK",    "USA",    40.7549,  -73.9840, 12, "America/New_York", 1),
    ("la",      "LOS ANGELES", "USA",    34.0522, -118.2437, 11, "America/Los_Angeles", 0),
    ("tokyo",   "TOKYO",       "JAPAN",  35.6762,  139.6503, 11, "Asia/Tokyo", 0),
    ("london",  "LONDON",      "UK",     51.5074,   -0.1278, 11, "Europe/London", 0),
    ("chennai", "CHENNAI",     "INDIA",  13.0827,   80.2707, 11, "Asia/Kolkata", 0),
    ("rio",     "RIO",         "BRAZIL", -22.9068,  -43.1729, 11, "America/Sao_Paulo", 0),
]

# city_id, location_id, name, lat, lon, radius_km, activity_bias
LOCATIONS = [
    ("nyc", "nyc-midtown",    "MIDTOWN MANHATTAN",  40.7549, -73.9840, 1.8, 0.95),
    ("nyc", "nyc-fidi",       "FINANCIAL DISTRICT", 40.7075, -74.0113, 1.4, 0.80),
    ("nyc", "nyc-queens",     "QUEENS",             40.7282, -73.7949, 4.0, 0.88),
    ("nyc", "nyc-brooklyn",   "BROOKLYN",           40.6782, -73.9442, 4.0, 0.76),
    ("nyc", "nyc-bronx",      "BRONX",              40.8448, -73.8648, 3.6, 0.52),
    ("nyc", "nyc-harlem",     "HARLEM",             40.8116, -73.9465, 2.0, 0.48),
    ("nyc", "nyc-qbridge",    "QUEENSBORO BRIDGE",  40.7570, -73.9540, 0.9, 0.71),
    ("nyc", "nyc-bbridge",    "BROOKLYN BRIDGE",    40.7061, -73.9969, 0.9, 0.69),
    ("nyc", "nyc-centralpark","CENTRAL PARK",       40.7829, -73.9654, 2.4, 0.62),
    ("nyc", "nyc-chelsea",    "CHELSEA",            40.7465, -74.0014, 1.3, 0.58),
    ("nyc", "nyc-soho",       "SOHO",               40.7233, -74.0030, 1.1, 0.55),
    ("nyc", "nyc-uws",        "UPPER WEST SIDE",    40.7870, -73.9754, 2.0, 0.45),
    ("nyc", "nyc-les",        "LOWER EAST SIDE",    40.7150, -73.9843, 1.2, 0.50),
    ("nyc", "nyc-staten",     "STATEN ISLAND",      40.5795, -74.1502, 5.0, 0.22),

    ("la", "la-downtown",  "DOWNTOWN LA",   34.0407, -118.2468, 2.2, 0.82),
    ("la", "la-hollywood", "HOLLYWOOD",     34.0928, -118.3287, 2.4, 0.74),
    ("la", "la-venice",    "VENICE BEACH",  33.9850, -118.4695, 1.8, 0.55),
    ("la", "la-santamon",  "SANTA MONICA",  34.0195, -118.4912, 2.0, 0.61),
    ("la", "la-koreatown", "KOREATOWN",     34.0578, -118.3009, 1.6, 0.48),

    ("tokyo", "tk-shibuya",  "SHIBUYA",   35.6580, 139.7016, 1.6, 0.86),
    ("tokyo", "tk-shinjuku", "SHINJUKU",  35.6938, 139.7034, 1.8, 0.79),
    ("tokyo", "tk-akihabara","AKIHABARA", 35.6987, 139.7730, 1.2, 0.66),
    ("tokyo", "tk-ginza",    "GINZA",     35.6717, 139.7650, 1.2, 0.52),

    ("london", "ln-city",       "CITY OF LONDON", 51.5155, -0.0922, 1.6, 0.77),
    ("london", "ln-westminster","WESTMINSTER",    51.4995, -0.1248, 1.6, 0.71),
    ("london", "ln-camden",     "CAMDEN",         51.5390, -0.1426, 1.6, 0.55),
    ("london", "ln-canary",     "CANARY WHARF",   51.5054, -0.0235, 1.4, 0.63),

    ("chennai", "ch-tnagar",   "T. NAGAR",     13.0418, 80.2341, 1.6, 0.68),
    ("chennai", "ch-marina",   "MARINA BEACH", 13.0500, 80.2824, 2.2, 0.59),
    ("chennai", "ch-anna",     "ANNA NAGAR",   13.0850, 80.2101, 1.8, 0.47),
    ("chennai", "ch-omr",      "OMR CORRIDOR", 12.9010, 80.2279, 3.2, 0.41),

    ("rio", "rio-copacabana", "COPACABANA", -22.9711, -43.1822, 1.8, 0.64),
    ("rio", "rio-centro",     "CENTRO",     -22.9035, -43.1795, 1.8, 0.58),
    ("rio", "rio-ipanema",    "IPANEMA",    -22.9838, -43.2096, 1.4, 0.49),
]

# camera_id, label, city_id, location_id, heading
CAMERAS = [
    ("CAM-01", "TIMES SQ NORTH",     "nyc", "nyc-midtown",     15),
    ("CAM-02", "BRYANT PARK EAST",   "nyc", "nyc-midtown",     95),
    ("CAM-03", "WALL ST PLAZA",      "nyc", "nyc-fidi",       210),
    ("CAM-04", "BROOKLYN BR SOUTH",  "nyc", "nyc-bbridge",    170),
    ("CAM-05", "QUEENS PLAZA",       "nyc", "nyc-queens",      60),
    ("CAM-06", "PROSPECT PARK W",    "nyc", "nyc-brooklyn",   275),
    ("CAM-07", "MIDTOWN 42ND",       "nyc", "nyc-midtown",    340),
    ("CAM-08", "QUEENSBORO SPAN",    "nyc", "nyc-qbridge",     80),
    ("CAM-09", "HARLEM 125TH",       "nyc", "nyc-harlem",      10),
    ("CAM-10", "CENTRAL PK RESVR",   "nyc", "nyc-centralpark",190),
    ("CAM-11", "CHELSEA PIERS",      "nyc", "nyc-chelsea",    250),
    ("CAM-12", "BRONX GRAND CONC",   "nyc", "nyc-bronx",       30),

    ("CAM-20", "PERSHING SQUARE",    "la", "la-downtown",     120),
    ("CAM-21", "HOLLYWOOD BLVD",     "la", "la-hollywood",     45),
    ("CAM-22", "VENICE BOARDWALK",   "la", "la-venice",       300),

    ("CAM-30", "SHIBUYA CROSSING",   "tokyo", "tk-shibuya",   200),
    ("CAM-31", "SHINJUKU EAST",      "tokyo", "tk-shinjuku",   85),

    ("CAM-40", "BANK JUNCTION",      "london", "ln-city",     140),
    ("CAM-41", "WESTMINSTER BR",     "london", "ln-westminster", 55),

    ("CAM-50", "T NAGAR MAIN",       "chennai", "ch-tnagar",   25),
    ("CAM-51", "MARINA PROMENADE",   "chennai", "ch-marina",  100),

    ("CAM-60", "COPACABANA SOUTH",   "rio", "rio-copacabana", 180),
]


def _jitter(value, spread):
    return value + random.uniform(-spread, spread)


def seed_reference_data(app):
    """Insert cities/locations/cameras if missing. Idempotent."""
    now = time.time()
    with dbmod.connection(app.config["DATABASE"]) as conn:
        with dbmod.write_lock:
            conn.executemany(
                "INSERT INTO cities(id,name,country,latitude,longitude,default_zoom,timezone,is_primary) "
                "VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING",
                CITIES,
            )
            conn.executemany(
                "INSERT INTO locations(id,city_id,name,latitude,longitude,radius_km,activity_bias) "
                "VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING",
                [(lid, cid, name, lat, lon, rad, bias)
                 for (cid, lid, name, lat, lon, rad, bias) in LOCATIONS],
            )

            loc_index = {row["id"]: row for row in conn.execute("SELECT * FROM locations")}
            rng = random.Random(1962)  # stable camera placement between boots
            camera_rows = []
            for cam_id, label, city_id, loc_id, heading in CAMERAS:
                loc = loc_index.get(loc_id)
                if loc is None:
                    continue
                spread = min(0.012, loc["radius_km"] / 160.0)
                camera_rows.append((
                    cam_id, label, city_id, loc_id,
                    loc["latitude"] + rng.uniform(-spread, spread),
                    loc["longitude"] + rng.uniform(-spread, spread),
                    heading, "live", None, 1, now, now,
                ))
            conn.executemany(
                "INSERT INTO cameras(id,label,city_id,location_id,latitude,longitude,heading,"
                "status,stream_url,is_mock,last_status_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) "
                "ON CONFLICT(id) DO NOTHING",
                camera_rows,
            )

            conn.execute(
                "INSERT INTO users(handle,display_name,role,created_at) VALUES(?,?,?,?) "
                "ON CONFLICT(handle) DO NOTHING",
                ("operator", "OPERATOR", "analyst", now),
            )
            conn.commit()


def has_sightings(app):
    with dbmod.connection(app.config["DATABASE"]) as conn:
        row = conn.execute("SELECT COUNT(*) AS c FROM sightings").fetchone()
    return row["c"] > 0


def seed_demo_history(app, hours=24, count=140):
    """Backfill demo sightings so charts and predictions have history on first run.

    Produces clustered, path-like activity rather than uniform noise, because
    the prediction engine is only interesting when movement is coherent.
    """
    from .services import ai_analysis, prediction

    rng = random.Random(4821)
    now = time.time()

    with dbmod.connection(app.config["DATABASE"]) as conn:
        cities = dbmod.dictify_all(conn.execute("SELECT * FROM cities").fetchall())
        locations = {}
        for row in conn.execute("SELECT * FROM locations"):
            locations.setdefault(row["city_id"], []).append(dict(row))
        cameras = {}
        for row in conn.execute("SELECT * FROM cameras"):
            cameras.setdefault(row["city_id"], []).append(dict(row))

        # Weight cities so New York dominates, matching the network panel story.
        city_weights = {"nyc": 0.58, "la": 0.16, "tokyo": 0.10, "london": 0.08,
                        "chennai": 0.05, "rio": 0.03}
        weighted = []
        for city in cities:
            weighted.extend([city] * max(1, int(city_weights.get(city["id"], 0.05) * 100)))

        rows = []
        analyses = []
        seq = 0

        # Walk a few "patrol chains" per city: each chain is a sequence of
        # sightings drifting in a consistent direction over time.
        chains = []
        for city in cities:
            chain_count = max(1, int(round(city_weights.get(city["id"], 0.05) * 12)))
            for _ in range(chain_count):
                chains.append(city)

        per_chain = max(3, count // max(1, len(chains)))
        for city in chains:
            locs = locations.get(city["id"], [])
            if not locs:
                continue
            current = rng.choice(locs)
            heading = rng.uniform(0, 360)
            t = now - rng.uniform(0, hours * 3600)
            for _ in range(rng.randint(max(2, per_chain - 2), per_chain + 2)):
                heading = (heading + rng.gauss(0, 28)) % 360
                spread = min(0.02, current["radius_km"] / 120.0)
                lat = current["latitude"] + rng.uniform(-spread, spread)
                lon = current["longitude"] + rng.uniform(-spread, spread)
                speed = max(8.0, rng.gauss(34, 12))
                cam = None
                source = "citizen"
                if rng.random() < 0.45:
                    city_cams = [c for c in cameras.get(city["id"], [])
                                 if c.get("location_id") == current["id"]]
                    if city_cams:
                        cam = rng.choice(city_cams)
                        source = "camera"
                elif rng.random() < 0.2:
                    source = "network"

                base_conf = 55 + current["activity_bias"] * 25 + rng.gauss(0, 12)
                if source == "camera":
                    base_conf += 8
                confidence = max(18.0, min(99.0, base_conf))
                status = ("confirmed" if confidence >= 85 else
                          "unverified" if confidence < 55 else "active")
                if now - t > app.config["ACTIVE_WINDOW_MIN"] * 60 and status == "active":
                    status = "expired"

                seq += 1
                # Temporary unique value; rewritten to the id-derived ref below
                # so seeded and runtime refs follow the same scheme.
                ref = "TMP-%06d" % seq
                rows.append((
                    ref, city["id"], current["id"], current["name"], lat, lon,
                    t, t, t, confidence, status, source,
                    cam["id"] if cam else None,
                    "DEMO NETWORK",
                    _demo_description(rng, current["name"]),
                    None, None, heading, speed,
                    1 if confidence >= 80 else 0, 1,
                ))
                analyses.append((ref, confidence, current["activity_bias"], speed))

                t += rng.uniform(240, 1500)
                if t > now:
                    break
                if rng.random() < 0.55:
                    current = _drift_location(locs, current, heading, rng)

        with dbmod.write_lock:
            conn.executemany(
                "INSERT INTO sightings(ref,city_id,location_id,area,latitude,longitude,ts,"
                "created_at,updated_at,confidence,status,source,camera_id,reporter,description,"
                "image_path,video_path,direction,speed_kmh,ai_verified,is_demo) "
                "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                rows,
            )
            conn.commit()

            # Resolve ids while the temporary refs are still in place, then
            # rewrite every ref to the id-derived scheme used at runtime.
            id_by_ref = {r["ref"]: r["id"] for r in
                         conn.execute("SELECT id, ref FROM sightings")}
            conn.execute(
                "UPDATE sightings SET ref = 'SGT-' || printf('%04d', ? + id) "
                "WHERE ref LIKE 'TMP-%'",
                (sightings_service.REF_BASE,),
            )
            conn.commit()

            analysis_rows = []
            for ref, confidence, bias, speed in analyses:
                sid = id_by_ref.get(ref)
                if sid is None:
                    continue
                breakdown = ai_analysis.synthesize_breakdown(confidence, bias, speed, rng)
                analysis_rows.append((
                    sid, "demo", "DEMO ANALYSIS", 0, confidence,
                    breakdown["visual_match"], breakdown["motion_match"],
                    breakdown["pattern_match"], breakdown["location_match"],
                    breakdown["notes"], now,
                ))
            conn.executemany(
                "INSERT INTO sighting_analysis(sighting_id,engine,engine_label,is_real_model,"
                "probability,visual_match,motion_match,pattern_match,location_match,notes,created_at) "
                "VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(sighting_id) DO NOTHING",
                analysis_rows,
            )

            detections = []
            for row in conn.execute(
                "SELECT id, camera_id, ts, confidence FROM sightings "
                "WHERE camera_id IS NOT NULL"
            ):
                detections.append((row["camera_id"], row["id"], row["ts"],
                                   row["confidence"], "POSSIBLE SUBJECT DETECTED", 1))
            conn.executemany(
                "INSERT INTO camera_detections(camera_id,sighting_id,ts,confidence,summary,is_demo) "
                "VALUES(?,?,?,?,?,?)",
                detections,
            )
            conn.commit()

    for city in CITIES:
        prediction.recompute(app, city[0], broadcast=False)
    refresh_network_stats(app)


def _drift_location(locs, current, heading, rng):
    """Pick the next district, biased toward the current heading."""
    from .services.geo import bearing_deg, angular_delta

    scored = []
    for loc in locs:
        if loc["id"] == current["id"]:
            continue
        b = bearing_deg(current["latitude"], current["longitude"],
                        loc["latitude"], loc["longitude"])
        alignment = 1.0 - (angular_delta(b, heading) / 180.0)
        scored.append((max(0.05, alignment ** 2 * loc["activity_bias"]), loc))
    if not scored:
        return current
    total = sum(w for w, _ in scored)
    pick = rng.uniform(0, total)
    acc = 0.0
    for weight, loc in scored:
        acc += weight
        if acc >= pick:
            return loc
    return scored[-1][1]


DEMO_DESCRIPTIONS = [
    "Red and blue figure moving between rooftops.",
    "Witness reports web-line anchored to building facade.",
    "Fast-moving subject above street level, no ground contact.",
    "Blurred figure crossing between towers.",
    "Subject descended vertically then departed east.",
    "Camera caught two frames of a red-suited figure.",
    "Reported swinging arc across the avenue.",
    "Bystander video shows figure landing on fire escape.",
]


def _demo_description(rng, area):
    return "%s (%s)" % (rng.choice(DEMO_DESCRIPTIONS), area)


def _next_ref_number(conn):
    row = conn.execute(
        "SELECT ref FROM sightings ORDER BY id DESC LIMIT 1"
    ).fetchone()
    if not row:
        return 4800
    try:
        return int(str(row["ref"]).split("-")[-1])
    except (ValueError, IndexError):
        return 4800


def refresh_network_stats(app):
    """Recompute the cached per-city counters used by the global network panel."""
    now = time.time()
    cutoff = now - 86400
    with dbmod.connection(app.config["DATABASE"]) as conn:
        rows = conn.execute(
            "SELECT c.id AS city_id, "
            "  COUNT(s.id) AS total, "
            "  SUM(CASE WHEN s.ts >= ? THEN 1 ELSE 0 END) AS last_24h, "
            "  SUM(CASE WHEN s.confidence >= 85 THEN 1 ELSE 0 END) AS high_conf, "
            "  MAX(s.ts) AS last_ts "
            "FROM cities c LEFT JOIN sightings s ON s.city_id = c.id "
            "GROUP BY c.id",
            (cutoff,),
        ).fetchall()
        payload = [(r["city_id"], r["total"] or 0, r["last_24h"] or 0,
                    r["high_conf"] or 0, r["last_ts"], now) for r in rows]
        with dbmod.write_lock:
            conn.executemany(
                "INSERT INTO network_stats(city_id,total,last_24h,high_confidence,"
                "last_sighting_ts,updated_at) VALUES(?,?,?,?,?,?) "
                "ON CONFLICT(city_id) DO UPDATE SET total=excluded.total, "
                "last_24h=excluded.last_24h, high_confidence=excluded.high_confidence, "
                "last_sighting_ts=excluded.last_sighting_ts, updated_at=excluded.updated_at",
                payload,
            )
            conn.commit()
    return payload
